services:
    webapp:
        build:
            context: ./
        container_name: ssd_test-webapp
        ports:
            - "80:3000"
        environment:
            - AUTH_USERNAME=admin
            - AUTH_PASSWORD=2301831@sit.singaporetech.edu.sg
        restart: always
            
    sonarqube:
        image: sonarqube:latest
        container_name: sonarqube_prac
        depends_on:
            - postgredb
        ports:
            - "9000:9000"   # Web UI
            - "9092:9092"   # Internal communication
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://postgredb:5432/sonarqube
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/api/system/status"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 120s
    
    postgredb:
        image: postgres:15-alpine
        container_name: sonarqube_db_prac
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
            POSTGRES_DB: sonarqube
        volumes:
            - postgresql:/var/lib/postgresql/data  # Fixed path
        ports:
            - "5432:5432"  # Optional: for direct DB access

    # Local Git Server (Gitea)
    gitea:
        image: gitea/gitea:latest
        container_name: gitea_server
        depends_on:
            - gitea_db
        ports:
            - "3001:3000"   # Gitea web interface
            - "2222:22"     # SSH for Git operations
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=gitea_db:5432
            - GITEA__database__NAME=gitea
            - GITEA__database__USER=gitea
            - GITEA__database__PASSWD=gitea
        volumes:
            - gitea_data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped

    # Database for Gitea
    gitea_db:
        image: postgres:15-alpine
        container_name: gitea_db
        environment:
            POSTGRES_USER: gitea
            POSTGRES_PASSWORD: gitea
            POSTGRES_DB: gitea
        volumes:
            - gitea_db_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    gitea_data:
    gitea_db_data:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    postgresql: